const fs = require('fs');
const path = require('path');

const basePath = path.join('d:', 'XTOWN', 'AI-ATTENDENCE', 'Backend');

const structure = {
    'package.json': `{\n  "name": "ai-employee-attendance-summary-system",\n  "version": "1.0.0",\n  "description": "AI Employee Attendance Summary System",\n  "main": "src/server.js",\n  "scripts": {\n    "start": "node src/server.js",\n    "dev": "nodemon src/server.js"\n  },\n  "dependencies": {\n    "express": "^4.18.2",\n    "sequelize": "^6.32.1",\n    "pg": "^8.11.0",\n    "pg-hstore": "^2.3.4",\n    "jsonwebtoken": "^9.0.0",\n    "bcrypt": "^5.1.0",\n    "dotenv": "^16.3.1",\n    "@google/generative-ai": "^0.1.1"\n  }\n}`,
    '.env': `PORT=3000\nDB_HOST=localhost\nDB_USER=postgres\nDB_PASS=password\nDB_NAME=ai_attendance\nJWT_SECRET=your_jwt_secret_key\nGEMINI_API_KEY=your_gemini_api_key\n`,
    'README.md': `# AI Employee Attendance Summary System\n\nBackend API for managing attendance and generating AI summaries.\n`,
    'src/app.js': `const express = require('express');\nconst authRoutes = require('./modules/auth/auth.routes');\nconst employeeRoutes = require('./modules/employee/employee.routes');\nconst attendanceRoutes = require('./modules/attendance/attendance.routes');\nconst departmentRoutes = require('./modules/department/department.routes');\nconst dashboardRoutes = require('./modules/dashboard/dashboard.routes');\nconst reportRoutes = require('./modules/report/report.routes');\nconst aiRoutes = require('./modules/ai/ai.routes');\nconst errorMiddleware = require('./middlewares/error.middleware');\n\nconst app = express();\n\napp.use(express.json());\n\napp.use('/api/auth', authRoutes);\napp.use('/api/employees', employeeRoutes);\napp.use('/api/attendance', attendanceRoutes);\napp.use('/api/departments', departmentRoutes);\napp.use('/api/dashboard', dashboardRoutes);\napp.use('/api/reports', reportRoutes);\napp.use('/api/ai', aiRoutes);\n\napp.use(errorMiddleware);\n\nmodule.exports = app;\n`,
    'src/server.js': `require('dotenv').config();\nconst app = require('./app');\nconst { sequelize } = require('./config/db');\n\nconst PORT = process.env.PORT || 3000;\n\nconst startServer = async () => {\n  try {\n    await sequelize.authenticate();\n    console.log('Database connected successfully.');\n    app.listen(PORT, () => {\n      console.log(\`Server is running on port \${PORT}\`);\n    });\n  } catch (error) {\n    console.error('Unable to connect to the database:', error);\n  }\n};\n\nstartServer();\n`,
    'src/config/db.js': `const { Sequelize } = require('sequelize');\n\nconst sequelize = new Sequelize(process.env.DB_NAME, process.env.DB_USER, process.env.DB_PASS, {\n  host: process.env.DB_HOST,\n  dialect: 'postgres',\n});\n\nmodule.exports = { sequelize };\n`,
    'src/config/gemini.js': `const { GoogleGenerativeAI } = require('@google/generative-ai');\n\nconst genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);\n\nmodule.exports = genAI;\n`,
    'src/models/initModels.js': `const { sequelize } = require('../config/db');\nconst User = require('../modules/auth/user.model');\nconst Employee = require('../modules/employee/employee.model');\nconst Department = require('../modules/department/department.model');\nconst Attendance = require('../modules/attendance/attendance.model');\n\n// Define associations here if needed\n\nconst initModels = async () => {\n  await sequelize.sync();\n};\n\nmodule.exports = initModels;\n`,
    'src/modules/auth/auth.controller.js': `const authService = require('./auth.service');\n\nconst login = async (req, res, next) => {\n  try {\n    const result = await authService.login(req.body);\n    res.status(200).json(result);\n  } catch (error) {\n    next(error);\n  }\n};\n\nmodule.exports = {\n  login\n};\n`,
    'src/modules/auth/auth.service.js': `const User = require('./user.model');\nconst jwtUtil = require('../../utils/jwt');\nconst bcryptUtil = require('../../utils/bcrypt');\n\nconst login = async (credentials) => {\n  // Implement login logic here\n  return { token: 'mock-token' };\n};\n\nmodule.exports = {\n  login\n};\n`,
    'src/modules/auth/auth.routes.js': `const express = require('express');\nconst authController = require('./auth.controller');\n\nconst router = express.Router();\n\nrouter.post('/login', authController.login);\n\nmodule.exports = router;\n`,
    'src/modules/auth/user.model.js': `const { DataTypes } = require('sequelize');\nconst { sequelize } = require('../../config/db');\n\nconst User = sequelize.define('User', {\n  id: {\n    type: DataTypes.INTEGER,\n    primaryKey: true,\n    autoIncrement: true\n  },\n  username: {\n    type: DataTypes.STRING,\n    allowNull: false\n  },\n  password: {\n    type: DataTypes.STRING,\n    allowNull: false\n  },\n  role: {\n    type: DataTypes.ENUM('Admin', 'HR Manager', 'Department Manager', 'Employee'),\n    allowNull: false\n  }\n});\n\nmodule.exports = User;\n`,
    'src/modules/employee/employee.controller.js': `const employeeService = require('./employee.service');\n\nconst getAllEmployees = async (req, res, next) => {\n  try {\n    const employees = await employeeService.getAllEmployees();\n    res.status(200).json(employees);\n  } catch (error) {\n    next(error);\n  }\n};\n\nmodule.exports = {\n  getAllEmployees\n};\n`,
    'src/modules/employee/employee.service.js': `const Employee = require('./employee.model');\n\nconst getAllEmployees = async () => {\n  return await Employee.findAll();\n};\n\nmodule.exports = {\n  getAllEmployees\n};\n`,
    'src/modules/employee/employee.routes.js': `const express = require('express');\nconst employeeController = require('./employee.controller');\n\nconst router = express.Router();\n\nrouter.get('/', employeeController.getAllEmployees);\n\nmodule.exports = router;\n`,
    'src/modules/employee/employee.model.js': `const { DataTypes } = require('sequelize');\nconst { sequelize } = require('../../config/db');\n\nconst Employee = sequelize.define('Employee', {\n  id: {\n    type: DataTypes.INTEGER,\n    primaryKey: true,\n    autoIncrement: true\n  },\n  name: {\n    type: DataTypes.STRING,\n    allowNull: false\n  }\n});\n\nmodule.exports = Employee;\n`,
    'src/modules/attendance/attendance.controller.js': `const attendanceService = require('./attendance.service');\n\nconst createAttendance = async (req, res, next) => {\n  try {\n    const record = await attendanceService.createAttendance(req.body);\n    res.status(201).json(record);\n  } catch (error) {\n    next(error);\n  }\n};\n\nmodule.exports = {\n  createAttendance\n};\n`,
    'src/modules/attendance/attendance.service.js': `const Attendance = require('./attendance.model');\n\nconst createAttendance = async (data) => {\n  // Attendance can only be created\n  return await Attendance.create(data);\n};\n\nmodule.exports = {\n  createAttendance\n};\n`,
    'src/modules/attendance/attendance.routes.js': `const express = require('express');\nconst attendanceController = require('./attendance.controller');\n\nconst router = express.Router();\n\nrouter.post('/', attendanceController.createAttendance);\n\nmodule.exports = router;\n`,
    'src/modules/attendance/attendance.model.js': `const { DataTypes } = require('sequelize');\nconst { sequelize } = require('../../config/db');\n\nconst Attendance = sequelize.define('Attendance', {\n  id: {\n    type: DataTypes.INTEGER,\n    primaryKey: true,\n    autoIncrement: true\n  },\n  status: {\n    type: DataTypes.ENUM('Present', 'Absent', 'On Duty', 'Leave'),\n    allowNull: false\n  },\n  date: {\n    type: DataTypes.DATEONLY,\n    allowNull: false\n  }\n});\n\nmodule.exports = Attendance;\n`,
    'src/modules/department/department.controller.js': `const departmentService = require('./department.service');\n\nconst getDepartments = async (req, res, next) => {\n  try {\n    const departments = await departmentService.getDepartments();\n    res.status(200).json(departments);\n  } catch (error) {\n    next(error);\n  }\n};\n\nmodule.exports = {\n  getDepartments\n};\n`,
    'src/modules/department/department.service.js': `const Department = require('./department.model');\n\nconst getDepartments = async () => {\n  return await Department.findAll();\n};\n\nmodule.exports = {\n  getDepartments\n};\n`,
    'src/modules/department/department.routes.js': `const express = require('express');\nconst departmentController = require('./department.controller');\n\nconst router = express.Router();\n\nrouter.get('/', departmentController.getDepartments);\n\nmodule.exports = router;\n`,
    'src/modules/department/department.model.js': `const { DataTypes } = require('sequelize');\nconst { sequelize } = require('../../config/db');\n\nconst Department = sequelize.define('Department', {\n  id: {\n    type: DataTypes.INTEGER,\n    primaryKey: true,\n    autoIncrement: true\n  },\n  name: {\n    type: DataTypes.STRING,\n    allowNull: false\n  }\n});\n\nmodule.exports = Department;\n`,
    'src/modules/dashboard/dashboard.controller.js': `const dashboardService = require('./dashboard.service');\n\nconst getStatistics = async (req, res, next) => {\n  try {\n    const stats = await dashboardService.getStatistics();\n    res.status(200).json(stats);\n  } catch (error) {\n    next(error);\n  }\n};\n\nmodule.exports = {\n  getStatistics\n};\n`,
    'src/modules/dashboard/dashboard.service.js': `const getStatistics = async () => {\n  // Implement dashboard statistics logic here\n  return {};\n};\n\nmodule.exports = {\n  getStatistics\n};\n`,
    'src/modules/dashboard/dashboard.routes.js': `const express = require('express');\nconst dashboardController = require('./dashboard.controller');\n\nconst router = express.Router();\n\nrouter.get('/statistics', dashboardController.getStatistics);\n\nmodule.exports = router;\n`,
    'src/modules/report/report.controller.js': `const reportService = require('./report.service');\n\nconst getReport = async (req, res, next) => {\n  try {\n    const report = await reportService.getReport(req.query.type);\n    res.status(200).json(report);\n  } catch (error) {\n    next(error);\n  }\n};\n\nmodule.exports = {\n  getReport\n};\n`,
    'src/modules/report/report.service.js': `const getReport = async (type) => {\n  // type: Daily, Monthly, Yearly\n  return { reportType: type };\n};\n\nmodule.exports = {\n  getReport\n};\n`,
    'src/modules/report/report.routes.js': `const express = require('express');\nconst reportController = require('./report.controller');\n\nconst router = express.Router();\n\nrouter.get('/', reportController.getReport);\n\nmodule.exports = router;\n`,
    'src/modules/ai/ai.controller.js': `const aiService = require('./ai.service');\n\nconst getSummary = async (req, res, next) => {\n  try {\n    const summary = await aiService.generateSummary();\n    res.status(200).json({ summary });\n  } catch (error) {\n    next(error);\n  }\n};\n\nmodule.exports = {\n  getSummary\n};\n`,
    'src/modules/ai/ai.service.js': `const genAI = require('../../config/gemini');\n\nconst generateSummary = async () => {\n  // AI analyzes attendance records only\n  return "AI summary placeholder";\n};\n\nmodule.exports = {\n  generateSummary\n};\n`,
    'src/modules/ai/ai.routes.js': `const express = require('express');\nconst aiController = require('./ai.controller');\n\nconst router = express.Router();\n\nrouter.get('/summary', aiController.getSummary);\n\nmodule.exports = router;\n`,
    'src/shared/.gitkeep': ``,
    'src/middlewares/auth.middleware.js': `const jwtUtil = require('../utils/jwt');\n\nconst authenticate = (req, res, next) => {\n  // Implement auth middleware\n  next();\n};\n\nmodule.exports = authenticate;\n`,
    'src/middlewares/role.middleware.js': `const authorize = (roles) => {\n  return (req, res, next) => {\n    // Implement role-based access middleware\n    next();\n  };\n};\n\nmodule.exports = authorize;\n`,
    'src/middlewares/error.middleware.js': `const errorHandler = (err, req, res, next) => {\n  console.error(err.stack);\n  res.status(500).json({ message: err.message || 'Internal Server Error' });\n};\n\nmodule.exports = errorHandler;\n`,
    'src/utils/bcrypt.js': `const bcrypt = require('bcrypt');\n\nconst hashPassword = async (password) => {\n  return await bcrypt.hash(password, 10);\n};\n\nconst comparePassword = async (password, hash) => {\n  return await bcrypt.compare(password, hash);\n};\n\nmodule.exports = {\n  hashPassword,\n  comparePassword\n};\n`,
    'src/utils/jwt.js': `const jwt = require('jsonwebtoken');\n\nconst generateToken = (payload) => {\n  return jwt.sign(payload, process.env.JWT_SECRET, { expiresIn: '1d' });\n};\n\nconst verifyToken = (token) => {\n  return jwt.verify(token, process.env.JWT_SECRET);\n};\n\nmodule.exports = {\n  generateToken,\n  verifyToken\n};\n`,
    'src/utils/response.js': `const success = (res, data, message = 'Success') => {\n  return res.status(200).json({ success: true, message, data });\n};\n\nconst error = (res, message = 'Error', statusCode = 500) => {\n  return res.status(statusCode).json({ success: false, message });\n};\n\nmodule.exports = {\n  success,\n  error\n};\n`,
    'src/utils/geminiPrompt.js': `const buildPrompt = (data) => {\n  return \`Summarize the following attendance records: \${JSON.stringify(data)}\`;\n};\n\nmodule.exports = {\n  buildPrompt\n};\n`,
    'src/scripts/seed.js': `const { sequelize } = require('../config/db');\n\nconst seedDatabase = async () => {\n  try {\n    await sequelize.sync({ force: true });\n    console.log('Database synced and seeded!');\n  } catch (error) {\n    console.error('Error seeding database:', error);\n  }\n};\n\nseedDatabase();\n`,
    'src/uploads/.gitkeep': ``
};

// Create dirs and files
for (const [filePath, content] of Object.entries(structure)) {
    const fullPath = path.join(basePath, filePath);
    const dir = path.dirname(fullPath);
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(fullPath, content, 'utf8');
}
console.log('Backend structure generated successfully.');
